version: "3.7"
services:
  test-express-validator:
    image: "test-express-validator:v1"
    restart: always
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
        volume:
          nocopy: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
